CREATE TABLE IF NOT EXISTS etl_execution (
    id INT AUTO_INCREMENT PRIMARY KEY,
    start_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    end_time DATETIME NULL,
    status VARCHAR(20) NOT NULL,
    message TEXT NULL
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS etl_progress (
    table_name VARCHAR(128) PRIMARY KEY,
    rows_loaded BIGINT NULL,
    status VARCHAR(20) NULL,
    updated_at DATETIME NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;
